# Generated by Django 5.2.6 on 2026-05-10 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-album_date']},
        ),
        migrations.AddField(
            model_name='album',
            name='album_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='folder_name',
            field=models.CharField(default='default_album', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='album',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
